name: Publish Beta Package to NPM

on:
  push:
    branches:
      - development
    paths:
      - packages/**

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            eslint-config-ez:
              - packages/eslint-config-ez/**
            eslint-config-yc:
              - packages/eslint-config-yc/**
            stylelint-config-ez:
              - packages/stylelint-config-ez/**

      - name: Publish Package eslint-config-ez beta
        if: steps.changes.outputs.eslint-config-ez == 'true'
        continue-on-error: true
        run: npm run publish-eslint-ez:beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Package eslint-config-yc beta
        if: steps.changes.outputs.eslint-config-yc == 'true'
        continue-on-error: true
        run: npm run publish-eslint-yc:beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Package stylelint-config-ez beta
        if: steps.changes.outputs.stylelint-config-ez == 'true'
        continue-on-error: true
        run: npm run publish-stylelint-ez:beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
